// <auto-generated>
//     此文件为自动生成文件，请勿手改，重新绑定会覆盖。
// </auto-generated>

using Framework;
using TMPro;
using UnityEngine.Scripting;
using UnityEngine.UI;

namespace UI
{
    /// <summary>
    /// DialogPanel 的控件绑定
    /// </summary>
    [Preserve]
    public partial class DialogPanel : PanelController, UIView.IBindable
    {
        private Button _bK;
        private Image _roleA;
        private Image _roleB;
        private TextMeshProUGUI _dialogText;
        private TextMeshProUGUI _nameText;

        /// <summary>
        /// 由 UIView 在挂载后调用，写入预制体上绑定的控件、界面属性和过渡动画
        /// </summary>
        public void Bind(UIView view)
        {
            _bK = (Button)view.GetBinding("bK");
            _roleA = (Image)view.GetBinding("roleA");
            _roleB = (Image)view.GetBinding("roleB");
            _dialogText = (TextMeshProUGUI)view.GetBinding("dialogText");
            _nameText = (TextMeshProUGUI)view.GetBinding("nameText");

            Properties = (DialogPanelProperties)view.Properties;
            AnimIn = view.AnimIn;
            AnimOut = view.AnimOut;
        }
    }
}
