// <auto-generated>
//     此文件为自动生成文件，请勿手改，重新绑定会覆盖。
// </auto-generated>

using Framework;
using UnityEngine.Scripting;
using UnityEngine.UI;

namespace UI
{
    /// <summary>
    /// LoadingPanel 的控件绑定
    /// </summary>
    [Preserve]
    public partial class LoadingPanel : SceneController, UIView.IBindable
    {
        private Image _progressBar;

        /// <summary>
        /// 由 UIView 在挂载后调用，写入预制体上绑定的控件、界面属性和过渡动画
        /// </summary>
        public void Bind(UIView view)
        {
            _progressBar = (Image)view.GetBinding("progressBar");

            Properties = (LoadingPanelProperties)view.Properties;
            AnimIn = view.AnimIn;
            AnimOut = view.AnimOut;
        }
    }
}
